package com.lukafenir.ivy.grocery

import io.mockk.coEvery
import io.mockk.every
import io.mockk.mockk
import kotlinx.coroutines.flow.emptyFlow
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test

class RoomGroceryRepositoryTest {

    private val dao = mockk<GroceryDao>()
    private lateinit var repository: RoomGroceryRepository

    @BeforeEach
    fun setup() {
        every { dao.getAllItems() } returns emptyFlow()
        repository = RoomGroceryRepository(dao)
    }

    @Test
    @DisplayName("WHEN insert called THEN returns the ID generated by the DAO")
    fun insert_returnsGeneratedId() = runTest {
        val item = GroceryItem(name = "Milk")
        val generatedId = 42L
        coEvery { dao.insertItem(item) } returns generatedId

        val returnedId = repository.insert(item)

        assertEquals(generatedId, returnedId)
    }
}
